# Generated by Django 5.1.4 on 2025-02-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled')], max_length=20, null=True),
        ),
    ]
