# Generated by Django 5.1.4 on 2025-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Подтверждено'), ('reserved', 'в ожидании'), ('canceled', 'Отменено')], max_length=20, null=True),
        ),
    ]
